// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: demo.proto

package com.tianyl.grpcDemo.service;

public interface TimeResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpcDemo.TimeResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string msg = 1;</code>
   */
  java.lang.String getMsg();
  /**
   * <code>optional string msg = 1;</code>
   */
  com.google.protobuf.ByteString
      getMsgBytes();
}
