// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: demo.proto

package com.tianyl.grpcDemo.service;

public interface TimeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpcDemo.TimeRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>optional string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
